-- CreateTable
CREATE TABLE "organization" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" CHAR(50) NOT NULL,
    "status" INT4 NOT NULL,

    CONSTRAINT "organization_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tribe" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "id_organization" INT8 NOT NULL,
    "name" CHAR(50) NOT NULL,
    "status" INT4 NOT NULL,

    CONSTRAINT "tribe_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "repository" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "id_tribe" INT8 NOT NULL,
    "name" CHAR(50) NOT NULL,
    "state" CHAR(1) NOT NULL,
    "create_time" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "status" CHAR(1) NOT NULL,

    CONSTRAINT "repository_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "metrics" (
    "id_repository" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "coverage" FLOAT8 NOT NULL,
    "bugs" INT4 NOT NULL,
    "vulnerabilities" INT4 NOT NULL,
    "hotspot" INT4 NOT NULL,
    "code_smells" INT4 NOT NULL,

    CONSTRAINT "metrics_pkey" PRIMARY KEY ("id_repository")
);

-- AddForeignKey
ALTER TABLE "tribe" ADD CONSTRAINT "tribe_id_organization_fkey" FOREIGN KEY ("id_organization") REFERENCES "organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "repository" ADD CONSTRAINT "repository_id_tribe_fkey" FOREIGN KEY ("id_tribe") REFERENCES "tribe"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "metrics" ADD CONSTRAINT "metrics_id_repository_fkey" FOREIGN KEY ("id_repository") REFERENCES "repository"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
